spring:
  application:
    name: rosinka-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://193.38.235.104:54320/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:M8mGNW6NTlOjWpJMFpFs33nGpEWKCSr2z50JV3b5P0qUdWVduYaygCfHMGHuWla1}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true
server:
  port: ${SERVER_PORT:8080}
app:
  upload:
    dir: ${APP_UPLOAD_DIR:uploads/avatars}
logging:
  level:
    com.rosinka.backend: DEBUG
    org.hibernate.SQL: DEBUG
